language: cpp
compiler: gcc
os: linux
dist: bionic
services: docker
script: "(cd modules && make -j -Orecurse)"

deploy:
  provider: releases
  api_key:
    secure: jnOqjrzpfaj4U8TUfqGSR8ZSrKC8UzYlTKtKtEiULOohyFOuwcnd2acJbV08xaBLVXRxI1ZFTJf686KbDhsHX48AknrHpZWcIcxshGkMzClpfutvhXlvxXP6fps+NOBtbgqe/l83xYuPkMUACo0edPAi2VURh74IunB799RwY81243aFq8agIP0ZjkY4yVjWVMXew4ERoTOFUep5AAwCOe0j0AJn9d3d6JWgDLtMfTsclAmnwBIa6zO2k7/b311S4c1BqZKEYDuREUi9XaCeMpc+yxuXCIV3aecvR5W/gPqPYZ4wZEfEhgih71iJ+s81ZxtF7A6KhQP+hHi95pI3C5alEc9WCDSX9ZLbd2ZYqeJ9VbS/YH8zOkNt5HakbRakylaaMCWqy1v9gCagJNlBoHUm09Wg4qGRLgKLIhcJG4aSohV9bZVt/r16dcSFrFO8/J8T5QtN/kCbBAelQMmXZgG9e+2bTWWzUVnyHFEccde4x4V9pdnbXOHkOHxxhWXWatjJiPfkGK+GZa4efzeKgxRl9u2LVYhHjku48g15zPgyWjdgZ88oDUKCtnNaaWLbqzhUJCumj4cHIat9KqJxju91F3Hg7dHz4wrUsX2ge5h2GHmGFVKAZK9vLNJ6kIPvO9ScOmEXRGpWIV6p1PxPwaHG7LjmgDE/Zo5mgf3CHM8=
  skip_cleanup: true
  file:
    - "modules/funchook/prefix/debian-stable-x86.tar.xz"
    - "modules/funchook/prefix/debian-stable-x86_64.tar.xz"
    - "modules/funchook/prefix/debian-testing-x86.tar.xz"
    - "modules/funchook/prefix/debian-testing-x86_64.tar.xz"
  draft: false
  on:
    branch: master

before_deploy:
  - git config --local user.name "p5-vbnekit"
  - git config --local user.email "vbnekit@p5y.su"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
